// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbmbsclrgcnqaxmdsgfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndibWJzY2xyZ2NucWF4bWRzZ2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MjI1ODUsImV4cCI6MjA5MTI5ODU4NX0.mQnC6IatK3vRmz0R0nmS_tYi1G5cFRg-bRMOgn8UwiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});